import type { Language } from './types';

export const GEMINI_MODEL = 'gemini-2.5-flash';

// Fix: Consolidate all translations and constants into this file.
export const TRANSLATIONS: Record<Language, any> = {
  en: {
    searchPlaceholder: "Search for a recipe (e.g., 'chocolate cake')",
    searchButton: "Search",
    noRecipes: "No recipes found. Try a different search!",
    cookingTime: "Cooking Time",
    servings: "Servings",
    ingredients: "Ingredients",
    standardCook: "Standard Cook",
    thermomixCook: "Thermomix",
    instructions: "Instructions",
    backButton: "Back to Recipes",
    poweredBy: "Powered by Recipe AI",
    contactUs: "Contact Us",
    errorTitle: "Something went wrong!",
    initialPrompt: "Generate 8 popular and diverse recipes from around the world. Ensure one is a dessert. Provide details for standard and Thermomix cooking methods.",
    searchPrompt: (term: string) => `Generate 8 recipes based on the search term: "${term}". Provide details for standard and Thermomix cooking methods.`,
    allRecipes: "All Recipes",
    favorites: "Favorites",
    addToFavorites: "Add to Favorites",
    removeFromFavorites: "Remove from Favorites",
    noFavorites: "You haven't favorited any recipes yet. Click the heart icon on a recipe to save it here!",
    share: "Share",
    shareRecipe: "Share Recipe",
    copiedToClipboard: "Recipe copied to clipboard!",
    regenerateImage: "Regenerate Image",
    regenerating: "Regenerating...",
    nutrition: "Nutrition",
    calories: "Calories",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",
  },
  fr: {
    searchPlaceholder: "Rechercher une recette (ex: 'gâteau au chocolat')",
    searchButton: "Rechercher",
    noRecipes: "Aucune recette trouvée. Essayez une autre recherche !",
    cookingTime: "Temps de cuisson",
    servings: "Portions",
    ingredients: "Ingrédients",
    standardCook: "Cuisson Standard",
    thermomixCook: "Thermomix",
    instructions: "Instructions",
    backButton: "Retour aux recettes",
    poweredBy: "Propulsé par Recipe AI",
    contactUs: "Contactez-nous",
    errorTitle: "Une erreur est survenue !",
    initialPrompt: "Générez 8 recettes populaires et diverses du monde entier en français. Assurez-vous qu'une recette est un dessert. Fournissez des détails pour les méthodes de cuisson standard et Thermomix.",
    searchPrompt: (term: string) => `Générez 8 recettes en français basées sur le terme de recherche : "${term}". Fournissez des détails pour les méthodes de cuisson standard et Thermomix.`,
    allRecipes: "Toutes les recettes",
    favorites: "Favoris",
    addToFavorites: "Ajouter aux favoris",
    removeFromFavorites: "Retirer des favoris",
    noFavorites: "Vous n'avez pas encore de recettes favorites. Cliquez sur l'icône du cœur sur une recette pour l'enregistrer ici !",
    share: "Partager",
    shareRecipe: "Partager la recette",
    copiedToClipboard: "Recette copiée dans le presse-papiers !",
    regenerateImage: "Régénérer l'image",
    regenerating: "Régénération...",
    nutrition: "Nutrition",
    calories: "Calories",
    protein: "Protéines",
    carbs: "Glucides",
    fat: "Lipides",
  },
  ar: {
    searchPlaceholder: "ابحث عن وصفة (مثال: 'كعكة الشوكولاتة')",
    searchButton: "بحث",
    noRecipes: "لم يتم العثور على وصفات. جرب بحثًا مختلفًا!",
    cookingTime: "وقت الطهي",
    servings: "حصص",
    ingredients: "المكونات",
    standardCook: "الطبخ العادي",
    thermomixCook: "ثرمومكس",
    instructions: "التعليمات",
    backButton: "العودة إلى الوصفات",
    poweredBy: "مدعوم بواسطة Recipe AI",
    contactUs: "اتصل بنا",
    errorTitle: "حدث خطأ ما!",
    initialPrompt: "أنشئ 8 وصفات شائعة ومتنوعة من جميع أنحاء العالم باللغة العربية. تأكد من أن إحدى الوصفات هي حلوى. قدم تفاصيل لطرق الطهي القياسية والثرمومكس.",
    searchPrompt: (term: string) => `أنشئ 8 وصفات باللغة العربية بناءً على مصطلح البحث: "${term}". قدم تفاصيل لطرق الطهي القياسية والثرمومكس.`,
    allRecipes: "كل الوصفات",
    favorites: "المفضلة",
    addToFavorites: "إضافة إلى المفضلة",
    removeFromFavorites: "إزالة من المفضلة",
    noFavorites: "لم تقم بتفضيل أي وصفات بعد. انقر على أيقونة القلب على الوصفة لحفظها هنا!",
    share: "مشاركة",
    shareRecipe: "مشاركة الوصفة",
    copiedToClipboard: "تم نسخ الوصفة إلى الحافظة!",
    regenerateImage: "إعادة إنشاء الصورة",
    regenerating: "جارٍ الإنشاء...",
    nutrition: "التغذية",
    calories: "السعرات الحرارية",
    protein: "بروتين",
    carbs: "كربوهيدرات",
    fat: "دهون",
  }
};
